[package]
name = "traffic"
version = "0.1.0"
edition = "2021"

[dependencies]
routing  = { path = "routing" }
renderer = { path = "renderer" }

nalgebra = "0.32"
winit    = "0.29"

rand    = "0.8"
anyhow  = "1.0"
