[package]
name = "renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
routing = { path = "../routing" }

skia-safe = { version = "0.71", features = ["gl"] }

gl = "0.6"
glutin = "0.31"

winit = "0.29"
glutin-winit = "0.4"
raw-window-handle = "0.5"

image  = "0.24"
anyhow = "1.0"
